name = "ApodizationFunctions"
uuid = "1989e0ef-b035-4793-b6cd-86d79d787dd6"
authors = ["Arnold"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
